export const options = [
    { value: "Apple", label: "Apple" },
    { value: "Banana", label: "Banana" },
    { value: "Orange", label: "Orange" },
    { value: "Mango", label: "Mango" },
    { value: "Pineapple", label: "Pineapple" },
    { value: "Strawberry", label: "Strawberry" },
    { value: "Watermelon", label: "Watermelon" },
    { value: "Grape", label: "Grape" },
    { value: "Kiwi", label: "Kiwi" },
    { value: "Avocado", label: "Avocado" },
    { value: "Tomato", label: "Tomato" },
    { value: "Potato", label: "Potato" },
    { value: "Onion", label: "Onion" },
    { value: "Carrot", label: "Carrot" },
    { value: "Broccoli", label: "Broccoli" },
    { value: "Cucumber", label: "Cucumber" },
    { value: "Eggplant", label: "Eggplant" },
    { value: "Spinach", label: "Spinach" },
    { value: "Bell Pepper", label: "Bell Pepper" },
    { value: "Cabbage", label: "Cabbage" },
    { value: "Rice", label: "Rice" },
    { value: "Wheat", label: "Wheat" },
    { value: "Corn", label: "Corn" },
    { value: "Oat", label: "Oat" },
    { value: "Barley", label: "Barley" },
    { value: "Quinoa", label: "Quinoa" },
    { value: "Milk", label: "Milk" },
    { value: "Cheese", label: "Cheese" },
    { value: "Yogurt", label: "Yogurt" },
    { value: "Butter", label: "Butter" },
    { value: "Cream", label: "Cream" },
    { value: "Beef", label: "Beef" },
    { value: "Chicken", label: "Chicken" },
    { value: "Pork", label: "Pork" },
    { value: "Lamb", label: "Lamb" },
    { value: "Salmon", label: "Salmon" },
    { value: "Tuna", label: "Tuna" },
    { value: "Shrimp", label: "Shrimp" },
    { value: "Crab", label: "Crab" },
    { value: "Tractor", label: "Tractor" },
    { value: "Plow", label: "Plow" },
    { value: "Irrigation System", label: "Irrigation System" },
    { value: "Harvester", label: "Harvester" },
    { value: "Pruner", label: "Pruner" },
    { value: "Coffee", label: "Coffee" },
    { value: "Tea", label: "Tea" },
    { value: "Juice", label: "Juice" },
    { value: "Wine", label: "Wine" },
    { value: "Basil", label: "Basil" },
    { value: "Oregano", label: "Oregano" },
    { value: "Pepper", label: "Pepper" },
    { value: "Cinnamon", label: "Cinnamon" },
    { value: "Flour", label: "Flour" },
    { value: "Sugar", label: "Sugar" },
    { value: "Olive Oil", label: "Olive Oil" },
    { value: "Honey", label: "Honey" },
    { value: "Screwdriver", label: "Screwdriver" },
    { value: "Pliers", label: "Pliers" },
    { value: "Hammer", label: "Hammer" },
    { value: "Wrench", label: "Wrench" },
    { value: "Saw", label: "Saw" },
    { value: "Drill", label: "Drill" },
    { value: "Measuring Tape", label: "Measuring Tape" },
    { value: "Level", label: "Level" },
    { value: "Utility Knife", label: "Utility Knife" },
    { value: "Switch", label: "Switch" },
    { value: "Socket", label: "Socket" },
    { value: "Plug", label: "Plug" },
    { value: "Circuit Breaker", label: "Circuit Breaker" },
    { value: "Electrical Wire", label: "Electrical Wire" },
    { value: "Light Bulb", label: "Light Bulb" },
    { value: "Transformer", label: "Transformer" },
    { value: "Fuse", label: "Fuse" },
    { value: "Power Drill", label: "Power Drill" },
    { value: "Circular Saw", label: "Circular Saw" },
    { value: "Angle Grinder", label: "Angle Grinder" },
    { value: "Sander", label: "Sander" },
    { value: "Air Compressor", label: "Air Compressor" },
    { value: "Television", label: "Television" },
    { value: "Refrigerator", label: "Refrigerator" },
    { value: "Laptop", label: "Laptop" },
    { value: "Desktop Computer", label: "Desktop Computer" },
    { value: "Smartphone", label: "Smartphone" },
    { value: "Tablet", label: "Tablet" },
    { value: "Printer", label: "Printer" },
    { value: "Camera", label: "Camera" },
    { value: "Sedan Car", label: "Sedan Car" },
    { value: "Pickup Truck", label: "Pickup Truck" },
    { value: "SUV", label: "SUV" },
    { value: "Tractor", label: "Tractor" },
    { value: "Motorcycle", label: "Motorcycle" },
    { value: "Delivery Van", label: "Delivery Van" },
    { value: "Forklift", label: "Forklift" },
    { value: "Office Desk", label: "Office Desk" },
    { value: "Office Chair", label: "Office Chair" },
    { value: "Filing Cabinet", label: "Filing Cabinet" },
    { value: "Whiteboard", label: "Whiteboard" }
];